<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="">
  <eClassifiers xsi:type="ecore:EClass" name="WebService">
    <eStructuralFeatures xsi:type="ecore:EReference" upperBound="-1" eType="#//Interface"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Struct">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" eType="#//Attribute"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" eType="#//Struct" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binding"/>
  <eClassifiers xsi:type="ecore:EClass" name="Endpoint" eSuperTypes="#//Interface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="binding" eType="#//Binding"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute"/>
</ecore:EPackage>
